language: "en"

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
- name: EntitySynonymMapper
- name: ResponseSelector
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.2
  specific_intent_thresholds:
    ask_cat_related_question: 0.4

assistant_id: 20241203-093537-prompt-account

policies:
  - name: RulePolicy
    core_fallback_action_name: "action_general_query"
    core_fallback_threshold: 0.3
    enable_fallback_prediction: True
